name: mackerel-agent-plugins

on:
  push:
    paths: ['mackerel-agent-plugins-git/**']
    branches: [master]
  pull_request:
    paths: ['mackerel-agent-plugins-git/**']
    branches: [master]
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Makepkg Build and Check
        id: makepkg
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: mackerel-agent-plugins-git

      - name: Print Package Files
        run: |
          echo "Successfully created the following package archive"
          echo "Package: ${{ steps.makepkg.outputs.pkgfile0 }}"

  Deploy:
    if: ${{ github.event_name == 'push' }}
    needs: Test
    runs-on: ubuntu-latest

    environment:
      name: AUR
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: mackerel-agent-plugins-git
          pkgbuild: ./mackerel-agent-plugins-git/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: ${{ github.event.head_commit.message }}
